spring:
  application:
    name: kafkaPersister

  kafka:
    bootstrap-servers: kafka:9092

    consumer:
      topic: measurement
      group-id: my-group
      auto-offset-reset: earliest

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

    producer:
      queue: summary

  data:
    mongodb:
      uri: mongodb://admin:admin@mongodb-green-energy:27017/greenenergy